<!-- IF ADMIN_ALERT -->{L_ADR_ADMIN_ALERT}<br/><br/><!-- ENDIF -->
<form method="post" action="{S_CHARACTER_ACTION}">
<br />
<table width="100%" align="center" border="1">
	<tr>
		<th align="center" colspan="2">{L_TOWNMAP}</td>
	</tr>
	<tr>
		<td align="center" class="row2" width="20%"><span class="gen"><img src="adr/images/TownMap/{SAISON}/Icone_Prison.gif" /><br /><input type="submit" name="InfoPrison" value="{L_TOWNBOUTONINFO1}" class="mainoption" /><br /><br /><img src="adr/images/TownMap/{SAISON}/Icone_Banque.gif" /><br /><input type="submit" name="InfoBanque" value="{L_TOWNBOUTONINFO2}" class="mainoption" /><br /><br /><img src="adr/images/TownMap/{SAISON}/Icone_Maison.gif" /><br /><input type="submit" name="InfoMaison" value="{L_TOWNBOUTONINFO3}" class="mainoption" /><br /><br /><img src="adr/images/TownMap/{SAISON}/Icone_Forge.gif" /><br /><input type="submit" name="InfoForge" value="{L_TOWNBOUTONINFO4}" class="mainoption" /><br /><br /><img src="adr/images/TownMap/{SAISON}/Icone_Temple.gif" /><br /><input type="submit" name="InfoTemple" value="{L_TOWNBOUTONINFO5}" class="mainoption" /><br /><br /><img src="adr/images/TownMap/{SAISON}/Icone_Boutique.gif" /><br /><input type="submit" name="InfoBoutique" value="{L_TOWNBOUTONINFO6}" class="mainoption" /><br /><br /><img src="adr/images/TownMap/{SAISON}/Icone_Entrainement.gif" /><br /><input type="submit" name="InfoEntrainement" value="{L_TOWNBOUTONINFO7}" class="mainoption" /><br /><br /><img src="adr/images/TownMap/{SAISON}/Icone_Entrepot.gif" /><br /><input type="submit" name="InfoEntrepot" value="{L_TOWNBOUTONINFO8}" class="mainoption" /><br /><br /><img src="adr/images/TownMap/{SAISON}/Icone_Combat.gif" /><br /><input type="submit" name="InfoCombat" value="{L_TOWNBOUTONINFO9}" class="mainoption" /><br /><br /><img src="adr/images/TownMap/{SAISON}/Icone_Mine.gif" /><br /><input type="submit" name="InfoMine" value="{L_TOWNBOUTONINFO10}" class="mainoption" /><br /><br /><img src="adr/images/TownMap/{SAISON}/Icone_Enchantement.gif" /><br /><input type="submit" name="InfoEnchantement" value="{L_TOWNBOUTONINFO11}" class="mainoption" /><br /><br /><img src="adr/images/TownMap/{SAISON}/Icone_Clan.gif" /><br /><input type="submit" name="InfoClan" value="{L_TOWNBOUTONINFO12}" class="mainoption" /></span></td>
            <td align="center" class="row1"><img src="adr/images/TownMap/{SAISON}/Tuile_Tete.gif" alt="TOWN MAP Version 2 By One_Piece" /><br /><img src="adr/images/TownMap/{SAISON}/Tuile_Haut.gif "/><br /><img src="adr/images/TownMap/{SAISON}/Tuile_1_1.gif" /><a href="{U_TOWNMAP_PRISON}"><img src="adr/images/TownMap/{SAISON}/Tuile_1_2.gif" border="0" alt="{L_TOWNMAP_PRISON}" /></a><img src="adr/images/TownMap/{SAISON}/Tuile_1_3.gif"/><a href="{U_TOWNMAP_BANQUE}"><img src="adr/images/TownMap/{SAISON}/Tuile_1_4.gif" border="0" alt="{L_TOWNMAP_BANQUE}" /></a><img src="adr/images/TownMap/{SAISON}/Tuile_1_5.gif"/><a href="{U_TOWNMAP_MINE}"><img src="adr/images/TownMap/{SAISON}/Tuile_1_6.gif" border="0" alt="{L_TOWNMAP_MINE}" /></a><img src="adr/images/TownMap/{SAISON}/Tuile_1_7.gif"/><br /><img src="adr/images/TownMap/{SAISON}/Tuile_Milieu.gif"/><br /><img src="adr/images/TownMap/{SAISON}/Tuile_2_1.gif"/><a href="{U_TOWNMAP_ENCHANTEMENT}"><img src="adr/images/TownMap/{SAISON}/Tuile_2_2.gif" border="0" alt="{L_TOWNMAP_ENCHANTEMENT}" /></a><img src="adr/images/TownMap/{SAISON}/Tuile_2_3.gif"/><a href="{U_TOWNMAP_TEMPLE}"><img src="adr/images/TownMap/{SAISON}/Tuile_2_4.gif" border="0" alt="{L_TOWNMAP_TEMPLE}" /></a><img src="adr/images/TownMap/{SAISON}/Tuile_2_5.gif"/><a href="{U_TOWNMAP_BOUTIQUE}"><img src="adr/images/TownMap/{SAISON}/Tuile_2_6.gif" border="0" alt="{L_TOWNMAP_BOUTIQUE}" /></a><img src="adr/images/TownMap/{SAISON}/Tuile_2_7.gif"/><a href="{U_TOWNMAP_MAISON}"><img src="adr/images/TownMap/{SAISON}/Tuile_2_8.gif" border="0" alt="{L_TOWNMAP_MAISON}" /></a><img src="adr/images/TownMap/{SAISON}/Tuile_2_9.gif"/><br /><img src="adr/images/TownMap/{SAISON}/Tuile_Bas.gif"/><br /><img src="adr/images/TownMap/{SAISON}/Tuile_3_1.gif"/><a href="{U_TOWNMAP_FORGE}"><img src="adr/images/TownMap/{SAISON}/Tuile_3_2.gif" border="0" alt="{L_TOWNMAP_FORGE}" /></a><img src="adr/images/TownMap/{SAISON}/Tuile_3_3.gif"/><a href="{U_TOWNMAP_ENTRAINEMENT}"><img src="adr/images/TownMap/{SAISON}/Tuile_3_4.gif" border="0" alt="{L_TOWNMAP_ENTRAINEMENT}" /></a><img src="adr/images/TownMap/{SAISON}/Tuile_3_5.gif" border="0" alt="{L_TOWNMAP_COMBAT}" /><a href="{U_TOWNMAP_ENTREPOT}"><img src="adr/images/TownMap/{SAISON}/Tuile_3_6.gif" border="0" alt="{L_TOWNMAP_ENTREPOT}" /></a><img src="adr/images/TownMap/{SAISON}/Tuile_3_7.gif"/><a href="{U_TOWNMAP_CLAN}"><img src="adr/images/TownMap/{SAISON}/Tuile_3_8.gif" border="0" alt="{L_TOWNMAP_CLAN}" /></a><img src="adr/images/TownMap/{SAISON}/Tuile_3_9.gif"/><br /><a href="{U_TOWNMAP_COMBAT}"><img src="adr/images/TownMap/{SAISON}/Tuile_Monstre.gif" border="0" alt="{L_TOWNMAP_MONSTRE}" /></a><br /><a href="{U_TOWNMAP_COMBAT}"><img src="adr/images/TownMap/{SAISON}/Tuile_Monstre2.gif" border="0" alt="{L_TOWNMAP_MONSTRE}" /></a><br /><img src="adr/images/TownMap/{SAISON}/Tuile_Tete.gif" alt="TOWN MAP Version 2 By One_Piece" /></td>
	</tr>
</table>

</form>


<br clear="all" />