cp includes/admin_easymod.php.txt ../../../admin/admin_easymod.php
cp em_includes/em_functions.php ../../../admin/em_includes/em_functions.php
cp em_includes/em_cipher.php ../../../admin/em_includes/em_cipher.php
cp em_includes/em_schema.php ../../../admin/em_includes/em_schema.php
cp em_includes/em_modio.php ../../../admin/em_includes/em_modio.php
cp em_includes/em_ftp.php ../../../admin/em_includes/em_ftp.php
cp em_includes/parser_xml.php ../../../admin/em_includes/parser_xml.php
cp em_includes/index.htm ../../../admin/em_includes/index.htm
cp includes/sql/sql_builder.php ../../../includes/sql/sql_builder.php
cp includes/sql/sql_builder_mssql.php ../../../includes/sql/sql_builder_mssql.php
cp includes/sql/sql_builder_mysql.php ../../../includes/sql/sql_builder_mysql.php
cp includes/sql/sql_builder_postgresql.php ../../../includes/sql/sql_builder_postgresql.php
cp includes/sql/sql_parser.php ../../../includes/sql/sql_parser.php
cp includes/sql/sql_reserved_keywords.php ../../../includes/sql/sql_reserved_keywords.php
cp languages/lang_sql_parser.php ../../../language/lang_english/lang_sql_parser.php
cp languages/lang_easymod_english.php ../../../language/lang_nederlands/lang_easymod.php
cp languages/lang_easymod_english.php ../../../language/lang_hebrew/lang_easymod.php
cp languages/lang_easymod_english.php ../../../language/lang_english/lang_easymod.php
cp languages/lang_easymod_english.php ../../../language/lang_deutsch/lang_easymod.php
cp languages/lang_easymod_english.php ../../../language/lang_francais/lang_easymod.php
cp includes/mod_complete.tpl ../../../templates/Defaultdmin/mod_complete.tpl
cp includes/mod_header.tpl ../../../templates/Defaultdmin/mod_header.tpl
cp includes/mod_history.tpl ../../../templates/Defaultdmin/mod_history.tpl
cp includes/mod_history_details.tpl ../../../templates/Defaultdmin/mod_history_details.tpl
cp includes/mod_install.tpl ../../../templates/Defaultdmin/mod_install.tpl
cp includes/mod_login.tpl ../../../templates/Defaultdmin/mod_login.tpl
cp includes/mod_process.tpl ../../../templates/Defaultdmin/mod_process.tpl
cp includes/mod_settings.tpl ../../../templates/Defaultdmin/mod_settings.tpl
cp includes/mod_sql_body.tpl ../../../templates/Defaultdmin/mod_sql_body.tpl
cp includes/mod_preview.tpl ../../../templates/Defaultdmin/mod_preview.tpl
cp includes/mod_diy_body.tpl ../../../templates/Defaultdmin/mod_diy_body.tpl
cp includes/mod_help.tpl ../../../templates/Defaultdmin/mod_help.tpl
cp easymod.gif ../../../templates/Defaultmages/easymod.gif
cp modx_inside.png ../../../templates/Defaultmages/modx_inside.png
cp includes/emc.gif ../../../templates/Defaultmages/emc.gif
