copy includes\admin_easymod.php.txt ..\..\..\admin\admin_easymod.php
copy em_includes\em_functions.php ..\..\..\admin\em_includes\em_functions.php
copy em_includes\em_cipher.php ..\..\..\admin\em_includes\em_cipher.php
copy em_includes\em_schema.php ..\..\..\admin\em_includes\em_schema.php
copy em_includes\em_modio.php ..\..\..\admin\em_includes\em_modio.php
copy em_includes\em_ftp.php ..\..\..\admin\em_includes\em_ftp.php
copy em_includes\parser_xml.php ..\..\..\admin\em_includes\parser_xml.php
copy em_includes\index.htm ..\..\..\admin\em_includes\index.htm
copy includes\sql\sql_builder.php ..\..\..\includes\sql\sql_builder.php
copy includes\sql\sql_builder_mssql.php ..\..\..\includes\sql\sql_builder_mssql.php
copy includes\sql\sql_builder_mysql.php ..\..\..\includes\sql\sql_builder_mysql.php
copy includes\sql\sql_builder_postgresql.php ..\..\..\includes\sql\sql_builder_postgresql.php
copy includes\sql\sql_parser.php ..\..\..\includes\sql\sql_parser.php
copy includes\sql\sql_reserved_keywords.php ..\..\..\includes\sql\sql_reserved_keywords.php
copy languages\lang_sql_parser.php ..\..\..\language\lang_english\lang_sql_parser.php
copy languages\lang_easymod_english.php ..\..\..\language\lang_nederlands\lang_easymod.php
copy languages\lang_easymod_english.php ..\..\..\language\lang_hebrew\lang_easymod.php
copy languages\lang_easymod_english.php ..\..\..\language\lang_english\lang_easymod.php
copy languages\lang_easymod_english.php ..\..\..\language\lang_deutsch\lang_easymod.php
copy languages\lang_easymod_english.php ..\..\..\language\lang_francais\lang_easymod.php
copy includes\mod_complete.tpl ..\..\..\templates\Defaultdmin\mod_complete.tpl
copy includes\mod_header.tpl ..\..\..\templates\Defaultdmin\mod_header.tpl
copy includes\mod_history.tpl ..\..\..\templates\Defaultdmin\mod_history.tpl
copy includes\mod_history_details.tpl ..\..\..\templates\Defaultdmin\mod_history_details.tpl
copy includes\mod_install.tpl ..\..\..\templates\Defaultdmin\mod_install.tpl
copy includes\mod_login.tpl ..\..\..\templates\Defaultdmin\mod_login.tpl
copy includes\mod_process.tpl ..\..\..\templates\Defaultdmin\mod_process.tpl
copy includes\mod_settings.tpl ..\..\..\templates\Defaultdmin\mod_settings.tpl
copy includes\mod_sql_body.tpl ..\..\..\templates\Defaultdmin\mod_sql_body.tpl
copy includes\mod_preview.tpl ..\..\..\templates\Defaultdmin\mod_preview.tpl
copy includes\mod_diy_body.tpl ..\..\..\templates\Defaultdmin\mod_diy_body.tpl
copy includes\mod_help.tpl ..\..\..\templates\Defaultdmin\mod_help.tpl
copy easymod.gif ..\..\..\templates\Defaultmages\easymod.gif
copy modx_inside.png ..\..\..\templates\Defaultmages\modx_inside.png
copy includes\emc.gif ..\..\..\templates\Defaultmages\emc.gif
