<?php

/***************************************************************************
      This file was automatically generated by Admin FAQ Editor
 ***************************************************************************/

/***************************************************************************
 *
 *   This program is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 ***************************************************************************/
 
// 
// To add an entry to your FAQ simply add a line to this file in this format:
// $faq[] = array("question", "answer");
// If you want to separate a section enter $faq[] = array("--","Block heading goes here if wanted");
// Links will be created automatically
//
// DO NOT forget the ; at the end of the line.
// Do NOT put double quotes (") in your FAQ entries, if you absolutely must then escape them ie. \"something\"
//
// The FAQ items will appear on the FAQ page in the same order they are listed in this file
//

$faq[] = array("--", "Questions Générales");
$faq[] = array("Qu'est-ce que la Liste des Contacts ?", "La Liste des Contacts est un moyen par lequel vous pouvez facilement trouver et contacter d'autres utilisateurs et empêcher les autres utilisateurs de vous trouver et de vous contacter avec Prillian. Les listes comprennent une liste de contacts, une liste de gens ignorés, et une liste de gens non autorisés à vous contacter. Une liste de gens non autorisés est comme une version allégée de la liste de gens ignorés. Cela cache vos informations de contact de la liste des utilisateurs, mais ne vous empêche pas de les voir comme le fait la liste des gens ignorés.");
$faq[] = array("Ces listes sont-elles implémentées dans la messagerie ? Fonctionnent-elles dans d'autres parties du forum.", "Oui, les listes sont implémentées dans la messagerie. Non, elles ne marchent pas dans d'autres parties du forum, excepté pour le panneau de contrôle de la Gestion des Contacts. L'administrateur du forum peut installer et développer des versions de Liste des Contacts pour ajouter la fonctionnalité à d'autres parties des forums, comme les profils des utilisateurs, les sujets, la liste des membres, les messages privés, voire plus.");
$faq[] = array("Comment puis-je éditer ma liste des contacts ?", " Pour éditer votre liste des contacts, accédez simplement à la <a href=\"././contact.php\">Gestion des Contacts</a>");
$faq[] = array("Comment puis-je ajouter un utilisateur à ma Liste des Contacts?", "Accédez au panneau de contrôle et allez à la page de la liste en particulier où vous voulez ajouter un utilisateur. Alors entrez le nom de l'utilisateur dans le champ près du bas de la page et appuyer sur le bouton \"Ajouter l'utilisateur\".
<br />
<br />Pour ajouter plusieurs utilisateurs en une fois, accédez au panneau de contrôle, et cliquez sur le lien \" Ajouter de nouveaux contacts \". De cette page, vous pouvez entrer plusieurs noms d'utilisateurs et les ajouter à vos listes en une seule fois. 
<br />
<br />Il y a aussi des liens pour ajouter un utilisateur ou retirer un utilisateur de vos listes dans la fenêtre  \"Lire les messages\".");

$faq[] = array("--", "Utiliser la Liste des Contacts");
$faq[] = array("Quelles options la liste des contacts apporte-elle ?", "La liste des Contacts est la plus utile des trois listes. Avec elle, vous pouvez limiter l'apparition des utilisateurs de Prillian aux seuls contacts en ligne en ce moment (soit sur la messagerie, soit sur le forum). Vous pouvez aussi être averti quand un contact se connecte ou se déconnecte.");
$faq[] = array("Comment puis-je choisir d'être averti quand un contact se connecte ?", "Accédez au panneau de contrôle pour voir votre liste de contacts. Cliquez sur le lien \"Editer les options d'alerte de connexion et de déconnexion\". De cette page, vous pouvez choisir d'être averti quand certains utilisateurs se connectent. Cochez simplement les utilisateurs dont vous voulez être averti de la connexion et pressez le bouton \"Envoyer\". Pour cesser d'être averti sur un utilisateur, décochez-le et pressez \"Envoyer\".");
$faq[] = array("C'est quoi le bouton \"Contact\" dans la fenêtre \"Envoyer un message\"?", "Vous pouvez pressez ce bouton pour ouvrir une petite fenêtre avec une liste de vos contacts. La liste vous laisse rapidement voir qui est connecté et déconnecté et vous pouvez cliquer sur leurs noms pour les mettre dans le champ \"Nom d'utilisateur\" dans la fenêtre \"Envoyer un message\".");
$faq[] = array("Quelles options la liste des gens ignorés apporte-elle ?", "Quand un utilisateur est sur votre liste de gens ignorés, cet utilisateur ne peut vous envoyer aucun message
<br />instantané. De plus, l'utilisateur n'apparaîtra pas dans la liste des utilisateurs connectés dans Prillian.");
$faq[] = array("Quelles options la liste des gens non autorisés apporte-elle ?", "Quand un utilisateur est sur votre liste de gens non autorisés, l'utilisateur ne peut vous envoyer aucun message instantané. De plus, il ne pourra vous voir dans la liste des connectés dans Prillian.");

$faq[] = array("--", "   Problèmes avec la Liste des Contacts ");
$faq[] = array("Qui a écrit ce programme de Liste des Contacts ?", "Ce programme (dans sa forme non-modifiée) est produit, fourni et copyright de et par <a href=\"http://darkmods.sourceforge.net/\" target=\"_blank\">Thoul</a>. Il est basé et inclus du code de programmation du forum phpBB, qui (dans sa forme non-modifiée) est produit, fourni et copyright du et par le <a href=\"http://www.phpbb.com/\" target=\"_blank\">groupe phpBB</a>.
<br />Les deux programmes sont sous la licence générale publique GNU et peuvent être distribués gratuitement, voir les liens pour plus de détails.");
$faq[] = array("Pourquoi telle option n'est pas disponible ?", "Ce programme a été écrit et est sous licence du groupe phpBB (dans le cas du programme de forum) et Thoul (dans le cas de la messagerie instantanée). Si vous pensez qu'une option mériterait d'être ajoutée au programme Prillian alors visitez le site web darkmods.sourceforge.net et vérifiez qu'elle n'ait pas déjà été soumise sur les forums. Si ce n'est pas le cas, postez une demande d'option dans les forums ou sur Sourceforge.");
$faq[] = array("Qui dois-je contacter en cas d'abus ou d'utilisation illégale de cette Liste des Contacts ?", "Vous devriez contacter l'administrateur du forum. Si vous ne pouvez trouvez qui il est, essayez alors de joindre un des modérateurs du forum et demandez-lui qui contacter pour un abus avec Prillian. Si vous n'avez toujours pas de réponse, contactez alors le propriétaire du nom de domaine (trouvez-le grâce à une recherche Whois), et si le forum se trouve sur un hébergeur gratuit (en général yahoo, free.fr, f2s.com, etc.), la direction ou le service clientèle. Notez que Thoul n'a absolument aucun contrôle et ne peut en aucun cas être tenu pour responsable sur la manière dont le forum incriminé et Prillian sont gérés.
<br />Il est totalement inutile de contacter Thoul à propos d'actions illégales et abusives avec Prillian, si cela n'est pas directement lié au site web darkmods.sourceforge.net ou à un problème technique avec Prillian lui-même. Si vous envoyez un email à Thoul en relation avec des problèmes non-liés avec ses aspects techniques, n'espérez aucune réponse de sa part.");

?>
